---
# tasks file for ansible-role-cfn-ecs-tasks

- name: Create or remove role stack
  cloudformation:
    template: "{{ lookup('file','{{ task_definition_file }}') | from_json }}"
    stack_name: "{{ ecs_tasks_stack_name }}"
    state: "{{ ecs_tasks_stack_state|default('present') }}"
    region: "{{ region|default('us-west-2') }}"
    security_token: "{{ lookup('env','AWS_SESSION_TOKEN')|default(omit, true) }}"
    tags: "{{ ecs_tasks_tags }}"
